-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/wiki_teams.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wiki_teams (
  wt_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wt_name BLOB NOT NULL, wt_description BLOB DEFAULT NULL,
  wt_creator INTEGER UNSIGNED NOT NULL,
  wt_created BLOB NOT NULL
);

CREATE UNIQUE INDEX wt_name_unique ON /*_*/wiki_teams (wt_name);
