-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/wiki_team_roles_group_support.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__wiki_team_roles AS
SELECT
  wtr_team,
  wtr_instance,
  wtr_role
FROM /*_*/wiki_team_roles;
DROP TABLE /*_*/wiki_team_roles;


CREATE TABLE /*_*/wiki_team_roles (
    wtr_team VARCHAR(255) NOT NULL,
    wtr_instance VARCHAR(16) DEFAULT NULL,
    wtr_role BLOB NOT NULL
  );
INSERT INTO /*_*/wiki_team_roles (wtr_team, wtr_instance, wtr_role)
SELECT
  wtr_team,
  wtr_instance,
  wtr_role
FROM
  /*_*/__temp__wiki_team_roles;
DROP TABLE /*_*/__temp__wiki_team_roles;

CREATE UNIQUE INDEX wtr_team_instance_role ON /*_*/wiki_team_roles (wtr_team, wtr_instance, wtr_role);
