-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/wikifarm_session_cache.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikifarm_session_cache (
  keyname BLOB DEFAULT '' NOT NULL,
  value BLOB DEFAULT NULL,
  exptime BLOB NOT NULL,
  modtoken VARCHAR(17) DEFAULT '00000000000000000' NOT NULL,
  flags INTEGER UNSIGNED DEFAULT NULL,
  PRIMARY KEY(keyname)
);

CREATE INDEX exptime ON /*_*/wikifarm_session_cache (exptime);
