-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/wiki_team_roles_instance_path.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/wiki_team_roles
  ADD COLUMN wtr_instance_path VARCHAR(255) DEFAULT NULL;
