-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/simple_farmer_instances.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/simple_farmer_instances (
  sfi_id VARCHAR(16) NOT NULL,
  sfi_path VARCHAR(255) NOT NULL,
  sfi_display_name VARCHAR(255) NOT NULL,
  sfi_created BINARY(14) NOT NULL,
  sfi_touched BINARY(14) NOT NULL,
  sfi_db_prefix VARCHAR(17) NOT NULL,
  sfi_database VARCHAR(255) NOT NULL,
  sfi_meta LONGBLOB NOT NULL,
  sfi_config LONGBLOB NOT NULL,
  sfi_status VARCHAR(255) NOT NULL,
  UNIQUE INDEX sfi_path (sfi_path),
  UNIQUE INDEX sfi_storage_index (sfi_database, sfi_db_prefix),
  PRIMARY KEY(sfi_id)
) /*$wgDBTableOptions*/;
