-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/simple_farmer_processes.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/simple_farmer_processes (
  sfp_instance VARCHAR(16) NOT NULL,
  sfp_pid VARCHAR(255) NOT NULL,
  sfp_type VARCHAR(255) NOT NULL,
  sfp_started BINARY(14) NOT NULL,
  PRIMARY KEY(sfp_instance, sfp_pid)
) /*$wgDBTableOptions*/;
