-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/simple_farmer_instances_wiki_id_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/simple_farmer_instances
  ADD sfi_wiki_id VARCHAR(255) NOT NULL;
