-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/wikifarm_groups.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikifarm_groups (
  wfg_name VARCHAR(255) NOT NULL,
  wfg_index VARCHAR(255) NOT NULL,
  UNIQUE INDEX wfg_name_index (wfg_name),
  PRIMARY KEY(wfg_name)
) /*$wgDBTableOptions*/;
