-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/wiki_team_roles.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wiki_team_roles (
  wtr_team INT UNSIGNED NOT NULL,
  wtr_instance VARCHAR(16) DEFAULT NULL,
  wtr_role VARBINARY(255) NOT NULL,
  UNIQUE INDEX wtr_team_instance_role (wtr_team, wtr_instance, wtr_role)
) /*$wgDBTableOptions*/;
