-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/wiki_team_roles_group_support.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/wiki_team_roles
  CHANGE wtr_team wtr_team VARCHAR(255) NOT NULL;
