-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/wiki_teams.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wiki_teams (
  wt_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  wt_name VARBINARY(200) NOT NULL,
  wt_description VARBINARY(200) DEFAULT NULL,
  wt_creator INT UNSIGNED NOT NULL,
  wt_created BINARY(14) NOT NULL,
  UNIQUE INDEX wt_name_unique (wt_name),
  PRIMARY KEY(wt_id)
) /*$wgDBTableOptions*/;
