-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/simple_farmer_instances.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE simple_farmer_instances (
  sfi_id VARCHAR(16) NOT NULL,
  sfi_path VARCHAR(255) NOT NULL,
  sfi_display_name VARCHAR(255) NOT NULL,
  sfi_created TIMESTAMPTZ NOT NULL,
  sfi_touched TIMESTAMPTZ NOT NULL,
  sfi_db_prefix VARCHAR(17) NOT NULL,
  sfi_database VARCHAR(255) NOT NULL,
  sfi_meta TEXT NOT NULL,
  sfi_config TEXT NOT NULL,
  sfi_status VARCHAR(255) NOT NULL,
  sfi_wiki_id VARCHAR(255) NOT NULL,
  PRIMARY KEY(sfi_id)
);

CREATE UNIQUE INDEX sfi_path ON simple_farmer_instances (sfi_path);

CREATE UNIQUE INDEX sfi_storage_index ON simple_farmer_instances (sfi_database, sfi_db_prefix);
