-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/simple_farmer_instances_pinned_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE simple_farmer_instances
  ADD sfi_pinned SMALLINT NOT NULL DEFAULT 0;
CREATE INDEX sfi_pinned ON simple_farmer_instances (sfi_pinned);
