-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/wiki_team_roles_group_support.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE wiki_team_roles
  ALTER wtr_team TYPE VARCHAR(255);
