-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/wiki_access_levels.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wiki_access_levels (
  wal_instance VARCHAR(16) NOT NULL,
  wal_instance_path VARCHAR(255) NOT NULL,
  wal_level VARBINARY(32) NOT NULL,
  PRIMARY KEY(wal_instance),
  UNIQUE INDEX wal_instance_path (wal_instance_path),
  INDEX wal_level (wal_level)
) /*$wgDBTableOptions*/;