-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceWikiFarm/db/wiki_teams.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wiki_teams (
  wt_id SERIAL NOT NULL,
  wt_name TEXT NOT NULL,
  wt_description TEXT DEFAULT NULL,
  wt_creator INT NOT NULL,
  wt_created TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(wt_id)
);

CREATE UNIQUE INDEX wt_name_unique ON wiki_teams (wt_name);
